Feature/action server config
RoBorregos/RoBorregos-Navigation-Testing pull request #1
Opened 2020-09-28 00:21 UTC by RicardoChapaRomero

### What does this PR do?
Adds Go_to and Move_base python classes to perform got_to action.

### Why is this PR important? 
Implements the first action of the navigation action server and sets the foundation for the next actions on the same server.

2020-09-28 00:50 UTC, paulvazbad approved these changes

2020-09-28 00:50 UTC, paulvazbad commented on catkin_ws/src/actions/scripts/navServer.py
> +    ao-toDefine
This is to avoid having different actionservers for each action right?

2020-09-28 00:50 UTC, paulvazbad commented on catkin_ws/src/actions/scripts/nav_actions/go_to.py
> +        with open('/home/ricardochapa/Desktop/RoBorregos/Roborregos-Navigation-Testing/catkin_ws/src/actions/data/goals.csv', 'r') as file:
Use a relative path instead of the full path.

2020-09-28 00:50 UTC, paulvazbad commented on catkin_ws/src/actions/scripts/nav_actions/go_to.py
> +                place=(place+1)%len(a)
rows in goals.csv will always be in the same order as places in a[] ? Maybe using a dict with key = place, value= [coords] is better

2020-09-28 00:51 UTC, paulvazbad commented
Please add a screenshot of catkin_make successfully building

2020-09-28 17:46 UTC, RicardoChapaRomero commented on catkin_ws/src/actions/scripts/navServer.py
> +    ao-toDefine
That's right. The idea is that each nav action should have its own class but all should be handled from the same action server.

2020-09-28 17:54 UTC, RicardoChapaRomero commented on catkin_ws/src/actions/scripts/nav_actions/go_to.py
> +                place=(place+1)%len(a)
Actually, this method was defined before I translated it into the class, I would have to look with @AuroTB to see if that is possible

2020-09-28 17:56 UTC, RicardoChapaRomero commented
Catkin Make correctly builded
![image](https://user-images.githubusercontent.com/47112298/94468399-f7888a00-0189-11eb-9742-72998f254f10.png)

2020-09-29 19:08 UTC, AuroTB requested changes

2020-09-29 19:08 UTC, AuroTB commented on catkin_ws/src/actions/scripts/nav_actions/go_to.py
> +                place=(place+1)%len(a)
yeah, you can actually implement it that way; instead of a list of pose/angular values you can store these in a [Pose Geometry Message](http://docs.ros.org/fuerte/api/geometry_msgs/html/msg/Pose.html).
Make sure to change how you send the goal to the move_vase server as well!

2020-09-29 19:08 UTC, AuroTB commented on catkin_ws/src/actions/scripts/nav_actions/move_base.py
> +    Pending = 0
remember that main_engine only accepts these valid states: PENDING, ACTIVE, SUCCEEDED, ABORTED

2020-09-29 19:08 UTC, AuroTB commented on catkin_ws/src/actions/scripts/nav_actions/move_base.py
> +        self._goal.target_pose.pose.position =  Point(goal_pose_given[0],goal_pose_given[1],0)
if you are going to implement it with a _Pose_, then you can actually eliminate most of this code and send it directly.

2020-10-12 15:42 UTC, RicardoChapaRomero commented on catkin_ws/src/actions/scripts/nav_actions/move_base.py
> +    Pending = 0
Yes, those are the states that the move base node can send as feedback, once I got them I translate them to the main engine's states.

2020-10-12 15:50 UTC, merged